<!-- Spin Wheel Modal -->
<div id="spin-wheel-modal" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4 hidden">
    <div class="bg-white rounded-2xl p-6 md:p-8 max-w-md w-full relative max-h-[90vh] overflow-y-auto">
        <button onclick="hideSpinWheel()" class="absolute top-4 right-4 p-2 hover:bg-gray-100 rounded-full transition-colors">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
        </button>

        <div class="text-center mb-6 md:mb-8">
            <div class="flex items-center justify-center gap-2 mb-2">
                <svg class="w-6 h-6 text-orange-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v13m0-13V6a2 2 0 112 2h-2zm0 0V5.5A2.5 2.5 0 109.5 8H12zm-7 4h14M5 12a2 2 0 110-4h14a2 2 0 110 4M5 12v7a2 2 0 002 2h10a2 2 0 002-2v-7"></path>
                </svg>
                <h2 class="text-2xl font-bold text-gray-800">Spin & Win!</h2>
            </div>
            <p class="text-gray-600">Get amazing discounts on local products</p>
        </div>

        <!-- Wheel -->
        <div class="relative w-64 h-64 md:w-80 md:h-80 mx-auto mb-6 md:mb-8">
            <div class="absolute inset-0 rounded-full border-4 border-gray-800 overflow-hidden">
                <div id="wheel" class="relative w-full h-full transition-transform duration-[3000ms] ease-out">
                    <!-- Wheel segments will be generated by JavaScript -->
                </div>
            </div>
            
            <!-- Pointer -->
            <div class="absolute top-0 left-1/2 transform -translate-x-1/2 -translate-y-2 z-10">
                <div class="w-0 h-0 border-l-4 border-r-4 border-b-8 border-l-transparent border-r-transparent border-b-gray-800"></div>
            </div>

            <!-- Center circle -->
            <div class="absolute inset-1/2 w-12 h-12 bg-gray-800 rounded-full transform -translate-x-1/2 -translate-y-1/2 flex items-center justify-center z-10">
                <svg class="w-6 h-6 text-yellow-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                </svg>
            </div>
        </div>

        <!-- Result -->
        <div id="spin-result" class="text-center mb-4 md:mb-6 p-4 bg-gradient-to-r from-orange-100 to-green-100 rounded-xl hidden text-gray-800">
            <h3 class="text-xl font-bold text-gray-800 mb-2">🎉 Congratulations!</h3>
            <p class="text-lg text-gray-700">You won: <span id="prize-text" class="font-bold text-orange-600"></span></p>
        </div>

        <!-- Spin Button -->
        <div class="text-center">
            <button
                id="spin-button"
                onclick="spinWheel()"
                class="px-6 py-3 md:px-8 md:py-3 rounded-full font-semibold text-white transition-all transform hover:scale-105 bg-gradient-to-r from-orange-500 to-green-600 hover:from-orange-600 hover:to-green-700"
            >
                Spin the Wheel!
            </button>
        </div>
    </div>
</div>
